### ISSUE TITLE
NServiceBus.Host crashes the process during message handling and doesn't recover

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.Host#95]
Version `7.0.0-beta0003` this morning crashed the process and generally stopped working after the following exception occurred in a message handler. 

```
Application: NServiceBus.Host.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException
   at System.Data.SqlClient.SqlConnection.GetOpenTdsConnection()
   at System.Data.SqlClient.SqlCommand.WaitForAsyncResults(System.IAsyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(System.IAsyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(System.IAsyncResult)
   at System.Threading.Tasks.TaskFactory`1[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].FromAsyncCoreLogic(System.IAsyncResult, System.Func`2<System.IAsyncResult,Int32>, System.Action`1<System.IAsyncResult>, System.Threading.Tasks.Task`1<Int32>, Boolean)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Dapper.SqlMapper+<ExecuteImplAsync>d__29.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Intreba.Enm.Server.UnlockOverrideScheduler+<<CheckSchedules>b__22_6>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```

**Comment by nillis** [comment]
The same behaviour occurs when Oracle exceptions (f.e. Connection request timeout) are thrown. I would expect the NSerivceBus.Host not to crash, but recovers/retries after a certain timeout.
