### ISSUE TITLE
Service installation fails to execute installers

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Host#99]
Using v5 with the host sample http://docs.particular.net/samples/hosting/nservicebus-host/ , when using RabbitMQ transport instead of the default, the Service installation as described here http://docs.particular.net/nservicebus/hosting/nservicebus-host/#installation runs "successfully" but logs the following output:

```
Failed to execute installers: System.Collections.Generic.KeyNotFoundException: The given key (NServiceBus.LocalAddress) was not present in the dictionary.
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\Build\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 91
   at NServiceBus.Settings.SettingsHolder.Get[T](String key) in C:\Build\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 23
   at NServiceBus.SettingsExtentions.LocalAddress(ReadOnlySettings settings) in C:\Build\src\NServiceBus.Core\SettingsExtentions.cs:line 66
   at NServiceBus.Features.TimeoutManager.Setup(FeatureConfigurationContext context) in C:\Build\src\NServiceBus.Core\Timeout\TimeoutManager.cs:line 40
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureState featureState, IEnumerable`1 featuresToActivate, FeatureConfigurationContext context) in C:\Build\src\NServiceBus.Core\Features\FeatureActivator.cs:line 240
   at NServiceBus.Features.FeatureActivator.SetupFeatures(FeatureConfigurationContext context) in C:\Build\src\NServiceBus.Core\Features\FeatureActivator.cs:line 116
   at NServiceBus.Configure.Initialize() in C:\Build\src\NServiceBus.Core\Configure.cs:line 115
   at NServiceBus.Bus.Create(BusConfiguration configuration) in C:\Build\src\NServiceBus.Core\Bus.cs:line 17
   at NServiceBus.GenericHost.PerformConfiguration(Action`1 moreConfiguration) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 119
   at NServiceBus.GenericHost.Install(String username) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 94
   at NServiceBus.Hosting.Windows.Installers.WindowsInstaller.RunInstall() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Hosting.Windows\Installers\WindowsInstaller.cs:line 57
```

**Comment by timbussmann** [comment]
also fails when just trying to start the endpoint manually. Does work with MSMQ.
